const uuid = require("uuid");

const zones = [
  {
    Délégations: [
      "Carthage ",
      " La Médina ",
      " Bab Bhar ",
      " Bab Souika ",
      " Omrane ",
      " Omrane Supérieur ",
      " Attahrir ",
      " El Menzah ",
      " Cité Alkhadhra ",
      " Bardo ",
      " Séjoumi ",
      " Azzouhour ",
      " Alhrairia ",
      " Sidi Hsine ",
      " Ouardia ",
      " Kabaria ",
      " Sidi Elbéchir ",
      " Jebel Jelloud ",
      " La Goulette ",
      " Le Kram ",
      " La Marsa",
    ],
    Nbre: "21",
    Gouvernorat: "TUNIS",
  },
  {
    Délégations: [
      "ARIANA Ville ",
      " Soukra ",
      " Raouède ",
      " Kalâat Andalous ",
      " Sidi Thabet ",
      " Cité Attadhamon ",
      " M’nihla",
    ],
    Nbre: "7",
    Gouvernorat: "ARIANA",
  },
  {
    Délégations: [
      "MANOUBA ",
      " Oued Ellil ",
      "Tebourba ",
      " Battan ",
      " Jedaida ",
      " Mornaguia ",
      " Borj Amri ",
      " Douar Hicher",
    ],
    Nbre: "8",
    Gouvernorat: "MANOUBA",
  },
  {
    Délégations: [
      "BEN AROUS ",
      " Nouvelle Médina ",
      " Mourouj ",
      " Hammam Lif ",
      " Hammam Chatt ",
      " Boumhel Bassatine ",
      " Ezzahra ",
      " Radès ",
      " Megrine ",
      " M’hamdia ",
      " Fouchana ",
      " Mornag",
    ],
    Nbre: "12",
    Gouvernorat: "BEN AROUS",
  },
  {
    Délégations: [
      "NABEUL ",
      " Dar Chaâbane Elfehri ",
      " Béni Khiar ",
      " Korba ",
      " Menzel Temime ",
      " Mida ",
      " Kelibia ",
      " Hammam Ghezaz ",
      " Haouaria ",
      " Takelsa ",
      " Slimane ",
      " Menzel Bouzelfa ",
      " Béni Khalled ",
      " Grombalia ",
      " Bouârgoub ",
      " Hammamet",
    ],
    Nbre: "16",
    Gouvernorat: "NABEUL",
  },
  {
    Délégations: [
      "BIZERTE Nord ",
      " Jarzouna ",
      " BIZERTE Sud ",
      " Sejnane ",
      " Joumine ",
      " Mateur ",
      " Ghezala ",
      " Menzel Bourguiba ",
      " Tinja ",
      " Utique ",
      " Ghar El Melh ",
      " Menzel Jemil ",
      " El Alia ",
      " Ras Jebel",
    ],
    Nbre: "14",
    Gouvernorat: "BIZERTE",
  },
  {
    Délégations: [
      "ZAGHOUAN ",
      " Zériba ",
      " Bir Mecharga ",
      " Fahs ",
      " Nadhour ",
      " Saouaf",
    ],
    Nbre: "6",
    Gouvernorat: "ZAGHOUAN",
  },
  {
    Délégations: [
      "SOUSSE Ville ",
      " Zaouia Ksiba Thrayat ",
      " SOUSSE Ryadh ",
      " SOUSSE Jawhara ",
      " SOUSSE Sidi Abdelhamid ",
      " Hammam SOUSSE ",
      " Akouda ",
      " Kalâa Elkébira ",
      " Sidi Bouali ",
      " Hergla ",
      " Enfidha ",
      " Bouficha ",
      " Koundar ",
      " Sidi Elheni ",
      " Msaken ",
      " Kalâa Ességhira",
    ],
    Nbre: "16",
    Gouvernorat: "SOUSSE",
  },
  {
    Délégations: [
      "MONASTIR ",
      " Ouerdanine ",
      " Sahline ",
      " Zéramdine ",
      " Béni Hassan ",
      " Jammel ",
      " Benbla ",
      " Moknine ",
      " Bekalta ",
      " Teboulba ",
      " Ksar Helal ",
      " Ksibet Medyouni ",
      " Sayada Lamta Bouhjar",
    ],
    Nbre: "13",
    Gouvernorat: "MONASTIR",
  },
  {
    Délégations: [
      "MAHDIA ",
      " Boumerdes ",
      " Ouled Chamekh ",
      " Chorbane ",
      " Hbira ",
      " Souassi ",
      " Eljem ",
      " Chebba ",
      " Malloulech ",
      " Sidi Alouane ",
      " Ksour Essef",
    ],
    Nbre: "11",
    Gouvernorat: "MAHDIA",
  },
  {
    Délégations: [
      "SFAX Ville ",
      " SFAX Ouest ",
      " Sakiet Ezzit ",
      " Sakiet Eddaier ",
      " SFAX sud ",
      " Tina ",
      " Agareb ",
      " Jebeniana ",
      "El Amra ",
      " El Hencha ",
      "Menzel chaker ",
      " Ghraiba ",
      " Bir Ali Ben Khelifa ",
      " Sekhira ",
      " Mahrès ",
      " Kerkennah",
    ],
    Nbre: "16",
    Gouvernorat: "SFAX",
  },
  {
    Délégations: [
      "BÉJA nord ",
      " BÉJA sud ",
      " Amdoun ",
      " Nefza ",
      " Teboursouk ",
      " Tibar ",
      " Testour ",
      " Goubellat ",
      " Mejez El Bab",
    ],
    Nbre: "9",
    Gouvernorat: "BÉJA",
  },
  {
    Délégations: [
      "JENDOUBA ",
      " JENDOUBA Nord ",
      " Boussalem ",
      " Tabarka ",
      " Ain Drahem ",
      " Fernana ",
      " Ghardimaou ",
      " Oued Mliz ",
      " Balta Bouaouene",
    ],
    Nbre: "9",
    Gouvernorat: "JENDOUBA",
  },
  {
    Délégations: [
      "KEF Ouest ",
      " KEF Est ",
      " Nebeur ",
      " Sakiet Sidi Youssef ",
      " Tejerouine ",
      " Kalâat sinane ",
      " Kalâa El khasba ",
      " Jerissa ",
      " Gsour ",
      " Dahmani ",
      " Le Sers",
    ],
    Nbre: "11",
    Gouvernorat: "KEF",
  },
  {
    Délégations: [
      "SILIANA nord ",
      " SILIANA sud ",
      " Bouarada ",
      "Gâafour ",
      " El Aroussa ",
      " Le Krib ",
      " Bourouis ",
      " Makther ",
      " Rouhia ",
      " Kesra ",
      " Bargou",
    ],
    Nbre: "11",
    Gouvernorat: "SILIANA",
  },
  {
    Délégations: [
      "Kairouan Nord ",
      "Kairouan Sud ",
      " Chebika ",
      " Sebikha ",
      " Oueslatia ",
      " Haffouz ",
      " El Ala ",
      " Hajeb El Ayoun ",
      " Nasrallah ",
      " Cherarda ",
      " Bouhajla",
    ],
    Nbre: "11",
    Gouvernorat: "KAIROUAN",
  },
  {
    Délégations: [
      "Sidi Bouzid Ouest ",
      " Sidi Bouzid Est ",
      " Jelma ",
      " Sabbalet Ouled Askar ",
      " Bir Hfay ",
      " Sidi Ali Benôun - Menzel Bouzayane ",
      " Meknassi ",
      " Souk Jedid ",
      " Mezouna ",
      " Regueb ",
      " Ouled Haffouz",
    ],
    Nbre: "12",
    Gouvernorat: "SIDI BOUZID",
  },
  {
    Délégations: [
      "Kasserine Nord ",
      " Kasserine Sud ",
      " Azzouhour ",
      " Hassi ferid ",
      " Sbitla ",
      " Sbiba ",
      " Jedliane ",
      " El Ayoun ",
      " Tela ",
      " Hidra ",
      " Foussana ",
      " Feriana ",
      " Mejel Bel Abbes",
    ],
    Nbre: "13",
    Gouvernorat: "KASSERINE",
  },
  {
    Délégations: [
      "Gabès ville ",
      " Gabès ouest ",
      " Gabès sud ",
      " Ghannouch ",
      " Metouia ",
      " Menzel habib ",
      " Hamma ",
      " Matmata ",
      " Matmata nouvelle ",
      " Mareth",
    ],
    Nbre: "10",
    Gouvernorat: "GABÈS",
  },
  {
    Délégations: [
      "Medenine Nord ",
      " Medenine Sud ",
      " Béni khedach ",
      " Ben Guerdene ",
      " Zazis ",
      " Jerba Houmet Souk ",
      " Jerba Midoun ",
      " Jerba Ajim ",
      " Sidi Makhlouf",
    ],
    Nbre: "9",
    Gouvernorat: "MEDENINE",
  },
  {
    Délégations: [
      "Gafsa Nord ",
      " Sidi Aich ",
      " El Ksar ",
      " Gafsa Sud ",
      " Moulares ",
      " Redyef ",
      " Métlaoui ",
      " El Mdhilla ",
      " El Guettar ",
      " Belkhir ",
      " Sned",
    ],
    Nbre: "11",
    Gouvernorat: "GAFSA",
  },
  {
    Délégations: ["Tozeur ", " Degueche ", " Tameghza ", " Nefta ", " Hezoua"],
    Nbre: "5",
    Gouvernorat: "TOUZER",
  },
  {
    Délégations: [
      "Tataouine Nord ",
      " Tataouine Sud ",
      " Smar ",
      " Bir Lahmer ",
      " Ghomrassen ",
      " Dhehiba ",
      " Remada",
    ],
    Nbre: "7",
    Gouvernorat: "TATAOUINE",
  },
  {
    Délégations: [
      "Kébili Sud ",
      " Kébili Nord ",
      " Souk El Ahad ",
      " Douz nord ",
      " Douz sud ",
      " El Faouar",
    ],
    Nbre: "6",
    Gouvernorat: "KÉBILI",
  },
];
exports.up = function (knex) {
  let data = [];
  zones.forEach((zone) => {
    zone.Délégations.forEach(async (delegation) => {
      const id = uuid.v1().toLocaleUpperCase();

      return data.push({
        id: id,
        name: "ZONE_" + delegation,
        gouvernorat: zone.Gouvernorat,
        city: delegation,
        agence: "1ba24600-e0c9-11eb-abdd-014ed3bc7a03",
      });
    });
  });
  console.log(data);
  return knex("zone").insert(
    data.map((d) => {
      return d;
    })
  );
};

exports.down = function (knex) {};
